### ISSUE TITLE
Error ld: library not found for -lACPAnalytics_iOS

### ISSUE THREAD

**Issue by itsashis4u** [adobe/react-native-acpanalytics#49] opened 2020-08-18 10:59 UTC
After upgrading react native version from v0.59.9 to v0.63. I am getting error when trying to build for ios.

### Expected Behaviour
Should build successfully

### Actual Behaviour
Getting the following error
`ld: library not found for -lACPAnalytics_iOS`

#### Steps to Reproduce
Open Xcode and try to build (Press Archive) the project

#### Platform and Version
```
Platform: iOS
RN Version: 0.63.0
Xcode: 11.4.1
@adobe/react-native-acpanalytics: "1.1.6"
@adobe/react-native-acpcore: "1.2.5"
```
#### Logs taken while reproducing problem
```
ld: warning: directory not found for option '-L/Users/<>/Library/Developer/Xcode/DerivedData/<>-hisbminqdfdpcigcbqkhawggzsha/Build/Intermediates.noindex/ArchiveIntermediates/VPT/BuildProductsPath/Release-iphoneos'
ld: library not found for -lACPAnalytics_iOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by nporter-adbe** [comment] 2020-08-18 16:42
This is most likely caused by 0.60 switching to using auto-linking to link native libraries. The quick fix for this is most likely running `pod install` in the `ios` directory of your project.

Ref:
https://github.com/adobe/react-native-acpanalytics#21-link
https://github.com/react-native-community/cli/blob/master/docs/autolinking.md

**Comment by itsashis4u** [comment] 2020-08-18 17:49
I had run `pod install`, still I got this error

**Comment by nporter-adbe** [comment] 2020-08-18 18:01
I was able to successfully run a fresh app on react native 0.63.2 after installing acpcore and acpanalytics. Here is a link to that repo: https://github.com/nporter-adbe/gitIssue49

The issue you are facing is most likely an issue with React Native during the upgrade process, if you search Google you can find many instances of a similar issues arising when upgrading to 0.6. I would suggest using the fixes in the github issues.
https://github.com/facebook/react-native/issues/28483
https://github.com/react-native-community/upgrade-support/issues/66

**Closed as completed** 2020-08-31 16:14 UTC
